// <auto-generated />
using System;
using ExamClient.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamClient.Migrations
{
    [DbContext(typeof(DB_API_Context))]
    partial class DBAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamClient.Models.Case", b =>
                {
                    b.Property<int>("Case_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Case_Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Case_Id");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("ExamClient.Models.Document", b =>
                {
                    b.Property<int>("Document_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Document_Id"));

                    b.Property<int?>("Case_Id")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Document_Id");

                    b.HasIndex("Case_Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ExamClient.Models.Document", b =>
                {
                    b.HasOne("ExamClient.Models.Case", null)
                        .WithMany("Delivers")
                        .HasForeignKey("Case_Id");
                });

            modelBuilder.Entity("ExamClient.Models.Case", b =>
                {
                    b.Navigation("Delivers");
                });
#pragma warning restore 612, 618
        }
    }
}
